<div align="center">

**LAPORAN PRAKTIKUM**

**ALGORITMA & PEMOGRAMAN**

**“TYPE DATA DAN VARIABEL”**

**Disusun Oleh :**

**Syasya Halwa Gazwani**

**2511531018**

**Dosen Pengampu:**

**Wahyudi.DR.. S.T.M.T**

**Asisten Praktikum:**

**Muhammad Galid Alvero**

<br>

 <img src="images/logo_unand.png" width="200">

<br>

**FAKULTAS TEKNOLOGI INFORMASI**

**DEPARTEMEN INFORMATIKA**

**UNIVERSITAS ANDALAS**

**2026**

</div>

## KATA PENGANTAR

Puji syukur penulis panjatkan atas kehadirat Tuhan Yang Maha Esa yang telah memberikan rahmat dan berkatnya, sehingga penulis dapat menyelesaikan laporan praktikum Algortima dan Pemrograman yang telah dilaksanakan sebagai pertemuan ke-2 untuk mata kuliah Praktikum Algortima dan Pemrograman. Praktikum ini berfokus pada pembahasan Type Data dan Variabel.

Melalui praktikum ini, hasil yang diharapkan adalah penulis dapat memahami dan mengimplementasikan secara langsung konsep Type Data dan Variabel pada real project.

Penulis menyadari bahwa laporan praktikum ini masih memiliki banyak kekurangan. Oleh karena itu, kritik dan saran yang membangun sangat diharapkan demi perbaikan dan pengembangan di masa mendatang.

Padang, 2026

---
# BAB I
# PENDAHULUAN

## 1.1 Latar Belakang
Dalam pemrograman Java, tipe data dan variabel merupakan dasar yang penting untuk dipahami karena untuk menyimpan dan mengolah berbagai jenis data di dalam program. Tipe data menentukan jenis nilai yang dapat disimpan, seperti bilangan bulat, bilangan desimal, karakter, dan nilai benar atau salah. Sementara itu, variabel digunakan sebagai tempat untuk menyimpan data yang dapat digunakan kembali selama program berjalan. Dengan memahami tipe data dan variabel, pengguna dapat membuat program yang lebih terstruktur dan sesuai dengan kebutuhan pengolahan data.

## 1.2 Tujuan
1. Memahami pengertian dan penggunaan tipe data serta variabel pada Java.
2. Dapat mengenali berbagai jenis tipe data.
3. Dapat membuat dan menggunakan variabel, serta menerapkannya dalam Java.

## 1.3 Manfaat
1. Menambah pemahaman mengenai dasar-dasar Java.
2. Dapat menyimpan dan mengolah, serta menampilkan data dengan lebih tepat.
3. Memiliki dasar yang lebih baik untuk mempelajari materi Java.

---
# BAB II
# PEMBAHASAN

## 2.1 Dasar Teori
Java merupakan bahasa pemrograman yang bersifat object-oriented dan memiliki aturan yang jelas dalam penggunaan data. Dalam Java, setiap data yang digunakan dalam program memiliki tipe data tertentu. Tipe data adalah jenis data yang menentukan nilai yang dapat disimpan serta operasi yang dapat dilakukan terhadap data tersebut. Secara umum, tipe data pada Java dibagi menjadi tipe data primitif dan tipe data non-primitif. Tipe data primitif merupakan tipe data dasar yang sudah tersedia dalam Java. Beberapa tipe data primitif yang umum digunakan yaitu int untuk bilangan bulat, double untuk bilangan desimal, char untuk satu karakter, boolean untuk nilai true atau false, serta byte, short, dan long untuk bilangan bulat dengan kapasitas yang berbeda. 

Selain itu terdapat float untuk bilangan pecahan. Sementara itu, tipe data non-primitif merupakan tipe data yang berupa objek atau referensi, contohnya String, array, dan class. Variabel adalah tempat yang digunakan untuk menyimpan suatu nilai di dalam memori selama program dijalankan. Setiap variabel dalam Java memiliki beberapa elemen penting, yaitu tipe data, nama variabel, dan nilai. Variabel juga dapat mengalami perubahan nilai selama program berjalan sesuai dengan kebutuhan.

Dalam penggunaannya, variabel harus dideklarasikan sebelum digunakan. Deklarasi berarti menentukan tipe data dan nama variabel, sedangkan pemberian nilai awal disebut inisialisasi. Java juga memiliki aturan penamaan variabel, seperti tidak boleh menggunakan spasi, tidak boleh diawali angka, dan tidak boleh menggunakan kata yang sudah menjadi keyword dalam Java. Pemahaman mengenai tipe data dan variabel menjadi dasar penting karena hampir setiap program Java membutuhkan proses penyimpanan, pengolahan, dan penggunaan data.

## 2.2 Kode Program

### 2.2.1 Program "Boolean_2511531018"
Boolean adalah tipe data dalam Java yang digunakan untuk menyimpan nilai yang hanya memiliki dua kemungkinan, yaitu true (benar) dan false (salah). Tipe data ini biasanya digunakan untuk membuat kondisi atau menentukan apakah suatu pernyataan memenuhi suatu keadaan tertentu.

In [8]:
is_lulus_1018 = True
is_cumlaude_1018 = True

#menggunakan boolean
nilai_1018 =85
batas_lulus_1018 = 75

# menentukan nilai boolean dari kondisi
status_kelulusan_1018 = nilai_1018 >= batas_lulus_1018 # hasilnya akan true

print("=== Check kelulusan ===")
print("Nilai: ", nilai_1018)
print("Apakah lulus? ", status_kelulusan_1018)
if is_lulus_1018 and is_cumlaude_1018:
   print("Selamat, Anda lulus dengan predikat Cumlaude!")

=== Check kelulusan ===
Nilai:  85
Apakah lulus?  True
Selamat, Anda lulus dengan predikat Cumlaude!


**Penjelasan :**
1. Bagian pertama kode ini berfungsi untuk membuat dua variabel boolean, yaitu is_lulus_1018 dan is_cumlaude_1018, yang masing-masing bernilai True. Variabel ini digunakan untuk menyatakan bahwa seseorang lulus dan mendapatkan predikat Cumlaude.
2. Bagian kedua berfungsi untuk menentukan status kelulusan berdasarkan nilai. nilai_1018 berisi nilai 85, sedangkan batas_lulus_1018 berisi nilai minimum kelulusan yaitu 75. Kondisi nilai_1018 >= batas_lulus_1018 akan menghasilkan nilai True karena 85 lebih besar dari 75.
3. Bagian ketiga berfungsi untuK menampilkan informasi nilai dan status kelulusan menggunakan print(). Program juga menggunakan if dengan operator and untuk mengecek apakah kedua kondisi, yaitu lulus dan Cumlaude, bernilai True. Jika keduanya benar, program akan menampilkan ucapan bahwa pengguna lulus dengan predikat Cumlaude.

### 2.2.2 Program "Konstanta_2511531018"

Konstanta adalah nilai yang tetap dan tidak dapat diubah selama program dijalankan. Konstanta digunakan ketika suatu nilai harus memiliki nilai yang sama dan tidak boleh mengalami perubahan. Dalam Java, konstanta biasanya dibuat menggunakan kata kunci final.

In [4]:
from typing import final
PI: final =3.14
print("pi: %f" % (PI))
jari_1018 = float(input('Masukkan nilai jari-jari: '))
luas_1018 = PI * jari_1018 * jari_1018
print("Luas lingkaran dengan jari-jari %.2f adalah %.2f" % (jari_1018, luas_1018))

pi: 3.140000
Luas lingkaran dengan jari-jari 8.00 adalah 200.96


**Penjelasan :**
1. Bagian pertama kode ini berfungsi untuk mengimpor final dari library typing, kemudian membuat konstanta PI dengan nilai 3.14. Nilai PI digunakan sebagai nilai tetap dalam perhitungan luas lingkaran.
2. Bagian kedua berfungsi untuk menampilkan nilai PI ke layar menggunakan print() dengan format %f.
3. Bagian ketiga berfungsi untuk meminta pengguna memasukkan nilai jari-jari lingkaran. Nilai tersebut diubah menjadi tipe data float agar dapat digunakan dalam perhitungan.
4. Bagian keempat berfungsi untuk menghitung luas lingkaran menggunakan nilai PI dan jari-jari yang telah dimasukkan.
5. Bagian kelima berfungsi untuk menampilkan hasil perhitungan luas lingkaran. Format %.2f digunakan agar nilai jari-jari dan luas ditampilkan dengan 2 angka di belakang koma.

### 2.2.3 Program "Numerik_2511531018"
Numerik adalah jenis data yang berupa angka dan dapat digunakan untuk melakukan operasi matematika, seperti penjumlahan, pengurangan, perkalian, dan pembagian. Dalam Java, data numerik dapat menggunakan beberapa tipe data, seperti int, double, float, long, short, dan byte.

In [5]:
# create a variable with integer value
a_1018=100
print("The type of variable having value", a_1018, " is ", type(a_1018))

# create a variable with float value
b_1018=10.2345
print("The type of variable having value", b_1018, " is ", type(b_1018))

# create a variable with complex value
c_1018=100+3j
print("The type of variable having value", c_1018, " is ", type(c_1018))

The type of variable having value 100  is  <class 'int'>
The type of variable having value 10.2345  is  <class 'float'>
The type of variable having value (100+3j)  is  <class 'complex'>


**Penjelasan :**
1. Bagian pertama kode ini berfungsi untuk membuat variabel a_1018 dengan nilai bilangan bulat (integer) yaitu 100. Kemudian type() digunakan untuk mengetahui tipe data dari variabel tersebut.
2. Bagian kedua berfungsi untuk membuat variabel b_1018 dengan nilai 10.2345 yang termasuk tipe data float atau bilangan desimal. Fungsi type() digunakan untuk menampilkan tipe datanya.
3. Bagian ketiga berfungsi untuk membuat variabel c_1018 dengan nilai 100+3j yang termasuk tipe data complex atau bilangan kompleks. Fungsi type() digunakan untuk mengetahui dan menampilkan tipe data variabel tersebut.
4. Secara keseluruhan, kode ini digunakan untuk mengenal dan membedakan tipe data numerik dalam Python, yaitu integer, float, dan complex.

### 2.2.4 Program "String_2511531018"
String adalah tipe data yang digunakan untuk menyimpan teks atau kumpulan karakter. String dapat berisi huruf, angka, simbol, maupun gabungan semuanya. Dalam Java, String ditulis menggunakan tanda petik dua (" ").

In [6]:
nama_1018 = "Syasya Halwa Gazwani"
jenis_kelamin_1018 = 'P'
alamat_1018 = """
    Jl.Irigasi
    Kec. Pauh
    Kota Padang
"""
agama_1018 = 'Islam'
print("Nama saya adalah: ",  nama_1018)
print("Jenis kelamin saya adalah: ",  jenis_kelamin_1018)
print("Alamat saya adalah: ",  alamat_1018)
print("Agama saya adalah: ",  agama_1018)

Nama saya adalah:  Syasya Halwa Gazwani
Jenis kelamin saya adalah:  P
Alamat saya adalah:  
    Jl.Irigasi
    Kec. Pauh
    Kota Padang

Agama saya adalah:  Islam


**Penjelasan :**
1. Bagian pertama kode ini berfungsi untuk membuat variabel nama_1018 yang menyimpan data berupa teks atau string, yaitu nama Syasya Halwa Gazwani.
2. Bagian kedua berfungsi untuk membuat variabel jenis_kelamin_1018 yang menyimpan karakter 'P' untuk menunjukkan jenis kelamin.
3. Bagian ketiga berfungsi untuk membuat variabel alamat_1018 yang menyimpan alamat dalam beberapa baris menggunakan tanda """. Dengan begitu, teks alamat dapat ditulis dalam lebih dari satu baris.
4. Bagian keempat berfungsi untuk membuat variabel agama_1018 yang menyimpan data teks berupa Islam.
5. Bagian terakhir berfungsi untuk menampilkan seluruh data yang telah disimpan dalam variabel menggunakan fungsi print(), yaitu nama, jenis kelamin, alamat, dan agama.

### 2.2.5 Program "Input_2511531018"
Input adalah proses memasukkan data dari pengguna ke dalam program. Input memungkinkan program menerima data secara langsung, misalnya nama, umur, nilai, atau pilihan pengguna. Dalam Java, salah satu cara yang umum digunakan untuk menerima input adalah menggunakan Scanner.

In [7]:
# memasukkan nilai panjang dan lebar persegi panjang
panjang_1018 = input('Masukkan nilai panjang persegi panjang: ')
lebar_1018 = input('Masukkan nilai lebar: ')
luas_1018 = int(panjang_1018) * int(lebar_1018) 
print("Luas =", luas_1018)

Luas = 24


**Penjelasan :**
1. Bagian pertama kode ini berfungsi untuk meminta pengguna memasukkan nilai panjang dan lebar persegi panjang menggunakan fungsi input(). Nilai yang dimasukkan awalnya akan dianggap sebagai tipe data string.
2. Bagian kedua berfungsi untuk menghitung luas persegi panjang. Fungsi int() digunakan untuk mengubah nilai panjang dan lebar dari string menjadi bilangan bulat agar dapat dilakukan operasi perkalian.
3. Bagian ketiga berfungsi untuk menampilkan hasil perhitungan luas persegi panjang menggunakan fungsi print(). Hasilnya ditampilkan dengan format "Luas = ...".

---
# BAB III
# KESIMPULAN

Berdasarkan praktikum yang telah dilakukan, dapat disimpulkan bahwa tipe data dan variabel merupakan dasar penting dalam pemrograman Java karena digunakan untuk menyimpan dan mengolah data. Tipe data seperti numerik, String, dan boolean memiliki fungsi yang berbeda sesuai dengan jenis data yang dibutuhkan. Selain itu, konstanta digunakan untuk menyimpan nilai yang tetap dan tidak dapat diubah selama program berjalan. Penggunaan input dengan Scanner juga memungkinkan program menerima data secara langsung dari pengguna. Dengan memahami konsep-konsep tersebut, pembuatan program Java menjadi lebih terstruktur dan sesuai dengan kebutuhan.

---
## DAFTAR PUSTAKA

[1] Python Software Foundation, “Built-in Types,” Python 3 Documentation. [Online]. Available: Built-in Types – Python Documentation. [Accessed: Sep. 12, 2026].

[2] Python Software Foundation, “Built-in Functions,” Python 3 Documentation. [Online]. Available: Built-in Functions – Python Documentation. [Accessed: Sep. 12, 2026].